### PR TITLE
Version 4.2.3

### PR DESCRIPTION
**Pull request by rmarkdev**

### CODE REVIEW

**Comment by jobenvil** [comment]
I don't understand why the **download link** was changed from **haiwen** to **rmarkdev**; some special reason?

**Comment by rmarkdev** [comment]
I can´t create a release under haiwen. So I created a release in my fork and linked it there.

**Comment by jobenvil** [comment]
I think this is not the way...

**Comment by rmarkdev** [comment]
When it is merged, will the release then be available under https://github.com/haiwen/seafile-rpi/releases/download/v4.2.3/seafile-server_4.2.3_pi.tar.gz ? If so, I just change it back to **haiwen**.
I´m new here, sorry for the circumstances.

**Comment by jobenvil** [comment]
ah, then is OK, but ensure please that you already tested it before:
http://manual.seafile.com/build_seafile/rpi.html  #Test the built package

**Comment by rmarkdev** [comment]
Yes I tested it as descibed. Worked fine for me.

**Pull request closed without merging**
